### ISSUE TITLE
Could you tell me how to extend POSSUM.

### ISSUE THREAD

**Issue by ka-taka123** [marksgraham/spin-echo-POSSUM#1]
Hi, I am trying to simulate SE-EPI using FSL-POSSUM. I would like to know how to extend the updated file to the current POSSUM. I copied the updated file and ran POSSUM, but it did not generate "pulse". Do I need to compile the updated files, such as pulse.cc?

**Comment by marksgraham** [comment]
Hi there,

Yes once you have replaced the POSSUM files with the files in this repo you need to recompile the files.

**Comment by ka-taka123** [comment]
Hi Mark, thanks for your reply.
I moved the current directory to $FSLDIR/src/possum and compiled, for example, "g++ pulse.cc". But the include path did not pass and it stopped with the following error. 

USER:/usr/local/fsl/src/possum$ g++ pulse.cc
pulse.cc:74:10: fatal error: libprob.h:  No such file or directory
 #include "libprob.h"
          ^~~~~~~~~~~
Could you give me some tips to consider when compiling?

**Comment by marksgraham** [comment]
What version of FSL do you have installed? My code was built on 5.0.10, and it may not work with later versions (even though POSSUM itself is mostly unchanged in these later versions, I believe).

**Comment by ka-taka123** [comment]
Thanks for your reply.
The FSL version is 5.0.10. The operating system is ubuntu 18.04.

**Comment by marksgraham** [comment]
You need to use the make commands to compile FSL, some more info here:
https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FslInstallation/SourceCode

Buy in brief try
cd $FSLDIR
make install

**Comment by ka-taka123** [comment]
Hi, thank you for the useful advice the other day.
This problem was resolved thanks to your support.
Thank you so much!

**Comment by marksgraham** [comment]
Glad to hear it!

**Comment by AdairMaldonado** [comment]
Hello Mark, I was reading what you answered in this problem and I would like to see if you can help me. I installed fsl 5.0.8 since I couldn't find version 5.0.10, although I don't think the problem is going in that direction and that is that I already replaced the src/possum folder with the one with Spin echo, I also replaced the .tcl file, so in the GUI I can select the SE, but when simulating, even though an image_abs is created, nothing makes sense. I have tried to compile using the sourcecode of the page, but unfortunately it sends me this message
/usr/local/fsl/config/default.mk:3: /usr/local/fsl/config/InstalledDir:-llvm14.0.0/systemvars.mk: No such file or directory
/usr/local/fsl/config/default.mk:4: /usr/local/fsl/config/InstalledDir:-llvm14.0.0/externallibs.mk: No such file or directory
make: *** No rule to make target `/usr/local/fsl/config/InstalledDir:-llvm14.0.0/externallibs.mk'. Stop.
I also tried your advice, but it didn't work. Do you have any idea what I could do to make it happen?

**Comment by marksgraham** [comment]
Hi there,

It looks like the compilation is the issue. Totally forgetting about spin-echo possum for now, are you able to compile the original FSL from source? Once you're able to do that, you should be able to sub in the new spin echo files and recompile. 

I'm not sure if I can help with your specific compilation issues, as they seem more specific to FSL then my code modifications, but it might be worth posting on the FSL forum (https://www.jiscmail.ac.uk/cgi-bin/webadmin?A0=fsl) as they should be able to help you.
